config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get '/profile', to:"users#profile", as: "profile"
      get '/profile/update', to: 'users#profile_settings', as: "update_profile"
      get '/login', to: 'sessions#new'
    end
  end
  resources :carts, only: [:destroy] do
    collection do
      patch '/update', to: "carts#update_quantity", as: "update_quantity"
      post '/add_item', to: "carts#add_item", as: "add_item"
      delete '/remove_item', to: "carts#remove_item", as: "remove_item"
      get '/display', to: "carts#show"
    end
  end 
  resources :products
  resources :orders do
    collection do
      patch '/:id/process_payment', to: 'orders#process_payment', as: "process_payment"
      post '/:id/pay', to: "orders#payment", as: "pay"
    end
  end
  resources :sessions, only: [] do
    collection do 
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
    end
  end
  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord

  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, through: :cart
  has_many :order_items, through: :orders
  validates :name, :email, presence: true, length: { maximum: 50 }
  validates :email, uniqueness: { case_sensitive: true }
  validates :password, length: { minimum: 6 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate, only: [:new, :create]
  skip_before_action :admin_user?, except: [:index, :destroy, :show, :edit]
  before_action :load_user, only: [:edit, :update, :show, :destroy]
  
  def index
    @users = User.all
  end

  def show
    
  end

  def new
    @user = User.new
  end

  def edit
    
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_later
      log_in @user
      @user.create_cart
      flash[:success] = "Welcome to the Sample App!"
      redirect_to profile_users_path
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params) 
      flash[:success] = "Profile updated"
      redirect_to profile_users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "User Removed Successfully"
    redirect_to users_path
  end

  def profile
    @user = current_user
    render 'show'
  end

  def profile_settings
    @user = current_user
    render 'edit'
  end

  private

  def load_user
    @user = (User.find(params[:id]) rescue nil)
    if @user.blank?
      flash[:danger] = "User does not exits"
      redirect_to profile_users_path 
    else
      @user
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :phone, :dob, :address, :country, :state)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render partial: 'shared/error_messages', locals: {object: @user} %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :dob %><br>
    <%= f.text_field :dob %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>
  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br>
    <%= f.text_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>
<br>

app/views/users/edit.html.erb
<h1>Update Details</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Users</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'View Profile', user unless user.admin? %></td>
      <td><%= link_to 'Remove user', user_path(user), method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to 'Back to admin profile', profile_users_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<%= "Hey Admin!, manage the site please" if @user.admin? %>
<p>
  <strong>NAME:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>EMAIL:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>DOB:</strong>
  <%= @user.dob %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>
<p>
  <strong>ADDRESS:</strong>
  <%= @user.address %>
</p>
<p>
  <strong>COUNTRY:</strong>
  <%= @user.country %>
</p>
<p>
  <strong>STATE:</strong>
  <%= @user.state %>
</p>
<h2> Past Orders </h2>
<%= render @user.orders %>
<br>
<%= link_to 'Users List', users_path if @user.admin? %>
<%= link_to 'Settings', update_profile_users_path  if current_user == @user %>
<%= link_to 'Change profile details', edit_user_path(@user) if current_user.admin? && !@user.admin?  %>
<%= link_to 'Add Products', new_product_path if @user.admin? %>
<%= link_to 'Your Cart', display_carts_path if current_user == @user %>
<%= link_to 'Manage Orders', orders_path if @user.admin? %>
<%= link_to 'View all products', products_path if current_user == @user %>
<%= link_to 'Log out', logout_sessions_path, method: :delete  if current_user == @user %>
<%= link_to 'Back to Admin Profile', profile_users_path unless current_user == @user %>
<br>
<p>Time now is <%= Time.now %> </p>
<p> You have logged in <%= session[:times_visited] %> times </p>