config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get '/profile', to:"users#profile", as: "profile"
      get '/profile/update', to: 'users#profile_settings', as: "update_profile"
      get '/login', to: 'sessions#new'
    end
  end
  resources :carts, only: [:destroy] do
    collection do
      patch '/update', to: "carts#update_quantity", as: "update_quantity"
      post '/add_item', to: "carts#add_item", as: "add_item"
      delete '/remove_item', to: "carts#remove_item", as: "remove_item"
      get '/display', to: "carts#show"
    end
  end 
  resources :products
  resources :orders do
    collection do
      patch '/:id/process_payment', to: 'orders#process_payment', as: "process_payment"
      post '/:id/pay', to: "orders#payment", as: "pay"
    end
  end
  resources :sessions, only: [] do
    collection do 
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
    end
  end
  root 'welcome#index'
end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items
  belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController 

  skip_before_action :admin_user?, except: [:index, :destroy, :edit, :update]
  before_action :load_order, except: [:index, :new, :create]
  before_action :authorised_user, only: :show
  before_action :is_valid_checkout?, only: :new
  def index
    @orders = Order.all
  end

  def show
    
  end

  def new
     
  end

  def edit

  end

  def create
    @order = current_user.orders.build
    perform_transaction
    redirect_to @order
  end

  def update
    @order.update_attributes(order_params) 
    redirect_to @order
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  def payment
    
  end

  def process_payment
    begin
      Order.transaction do
        @order.order_items.each do |item|
          item.product.update_attributes!(stock: item.product.stock - item.quantity)
        end
        details = order_params
        details.merge!({ status: "paid", transaction_id: SecureRandom.hex(10), payment_date: DateTime.now })
        @order.update_attributes!(details) 
        flash[:success] = "Your Payment transaction is successful. Order received successfully and will be delivered soon"
        redirect_to @order
      end
    rescue Exception => e
      flash[:danger] = e.message
      render 'payment'
    end
    OrderMailer.order_email(@order).deliver_later
  end

  private

  def order_params
    params.require(:order).permit(:status, :address, :country, :state, :zip_code, :card, :cvv, 
                                  :card_expiry_date, :payment_mode, :shipped_on, :delivered_on, 
                                  :payment_date)
  end

  def load_order
    @order = Order.find(params[:id]) rescue nil
    if @order.blank?
      flash[:danger] = "Order Does not exists"
      redirect_to profile_users_path
    end
  end

  def authorised_user
    unless @order.user == current_user || current_user.admin?
      flash[:danger] = "This order does not belongs to you"
      redirect_to profile_users_path 
    end
  end

  def is_valid_checkout?
    if current_user.cart.cart_items.count == 0
      flash[:danger] = "Your cart is empty, please add items"
      redirect_to display_carts_path
    else
      @order = Order.new
    end
  end

  def perform_transaction
    begin
      Order.transaction do              
        current_user.cart.cart_items.each do |item|
          details = { order_id: @order.id, product_id: item.product_id, price: item.product.price,
                     tax_rate: item.product.tax_rate, quantity: item.quantity, total_price: item.product.price * item.quantity * (1 + item.product.tax_rate / 100) }
          @order.order_items.build(details)
          item.destroy
        end
        details = order_params
        details.merge!({ amount: get_total_cost, tax: get_total_tax })
        @order.update_attributes!(details)
      end
    rescue Exception => e
      flash[:danger] = e.message
      render 'new'
    end
  end

  def get_total_cost
    total_cost = @order.order_items.inject(0){ |cost, item| cost += item.total_price}
  end

  def get_total_tax
    total_tax = @order.order_items.inject(0){ |cost, item| cost += item.price * item.tax_rate * item.quantity / 100 }
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<h2> Update Order Status </h2>
<%= form_for @order do |f| %>
<p>
  <%= f.label :status %><br>
  <%= f.text_field :status %>
</p>
<p>
  <%= f.label :shipped_on %><br>
  <%= f.text_field :shipped_on %>
</p>
<p>
  <%= f.label :delivered_on %><br>
  <%= f.text_field :delivered_on %>
</p>
<p>
  <%= f.submit "Update status" %>
</p>
<% end %>
<%= link_to 'Back', order_path(@order) %><br>

app/views/orders/_order.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>Date</th>
    <th>Status</th>
    <th>Transaction ID</th>
    <th>Total Amount</th>
    <th colspan="3"></th>
  </tr>
  <tr>
      <td><%= order.id %></td>
      <td><%= order.created_at.to_date %></td>
      <td><%= order.status %></td>
      <td><%= order.transaction_id %></td>
      <td><%= sprintf("%.2f", order.amount) %></td>
</table>
<%= link_to 'Order Details', order_path(order) %><br>

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
<h1>All Orders</h1>
<table>
  <tr>
    <th>ID</th>
    <th>Status</th>
    <th>User Name</th>
    <th>Total Amount</th>
    <th colspan="3"></th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.status %></td>
      <td><%= order.user.name %></td>
      <td><%= order.amount %></td>
      <td><%= link_to 'View Order Details', order_path(order) %></td>
      <td><%= link_to 'Remove Order', order_path(order), method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to 'Back to your profile', profile_users_path %>

app/views/orders/new.html.erb
<div class="wrapper">
<marquee behavior="alternate"><span class="marquee"><h2>Please confirm your order</h2></span></marquee>
</div>
<h2> Your Cart Contains </h2>
<table>
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Tax_rate</th>
    <th>Amount</th>
    <th colspan="3"></th>
  </tr>
  <% current_user.cart.cart_items.each do |cart_item| %>
    <tr>
      <td><%= cart_item.product.name %></td>
      <td><%= cart_item.quantity %></td>
      <td><%= cart_item.product.price %></td>
      <td><%= cart_item.product.tax_rate %></td>
      <td><%= sprintf("%.2f", cart_item.total_price) %></td>
  <% end %>
</table>
<br>
<%= "Total order amount will be: #{sprintf("%.2f",current_user.cart.sub_total)}" %><br>
<%= "Total order tax will be: #{sprintf("%.2f",current_user.cart.total_tax)}" %><br>
<br>
<%= link_to "Modify Cart", display_carts_path %><br>
<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :shipping_address %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>
  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :shipping_zip_code %><br>
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.submit "confirm order" %>
  </p>
<% end %>

app/views/orders/payment.html.erb
<h2> Payment Gateway </h2>
<%= form_for @order, url: url_for(process_payment_orders_path) do |f| %>
<p>
  <%= f.label :payment_mode %><br>
  <%= f.select :payment_mode, ['credit card', 'net banking'] %>
</p>
<p>
  <%= f.label :card_number %><br>
  <%= f.text_field :card %>
</p>
<p>
  <%= f.label :cvv %><br>
  <%= f.text_field :cvv %>
</p>
<p>
  <%= f.label :card_expiry_date %><br>
  <%= f.text_field :card_expiry_date %>
</p>
<p>
  <%= f.submit "confirm payment" %>
</p>
<% end %>
<%= link_to 'Back', order_path(@order) %><br>

app/views/orders/show.html.erb
<div class="wrapper">
  <marquee behavior="alternate"><span class="marquee">
    <h4>
      <% if @order.status == "unpaid" %>
        <%= "Your order payment is pending. Kindly make the payment otherwise order will be cancelled"  %>
      <% else %>
      <%= "your order status is #{@order.status}" %>
      <% end %>
    </h4></span>
  </marquee>
</div>
<h1>Order Details</h1>
<table>
  <tr>
    <th>ID</th>
    <th>Date</th>
    <th>Status</th>
    <th>TransactionID</th>
    <th>TotalAmount</th>
    <th>TotalTax</th>
    <th>Shipping address</th>
    <th>Payment Date</th>
    <th>Payment Mode</th>
    <th>Shipped_on</th>
    <th>Delivered_on</th>
    <th colspan="3"></th>
  </tr>
    <tr>
      <td><%= @order.id %></td>
      <td><%= @order.created_at.to_date %></td>
      <td><%= @order.status %></td>
      <td><%= @order.transaction_id %></td>
      <td><%= sprintf("%.2f", @order.amount) %></td>
      <td><%= sprintf("%.2f", @order.tax) %></td>
      <td><%= @order.address %></td>
      <td><%= @order.payment_date %></td>
      <td><%= @order.payment_mode %></td>
      <td><%= @order.shipped_on %></td>
      <td><%= @order.delivered_on %></td>
</table>
<%= link_to "Change status", edit_order_path(@order) if current_user.admin? %>
<h1>All Order Items</h1>
<table>
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Tax rate</th>
    <th>Amount</th>
    <th colspan="3"></th>
  </tr>
  <% @order.order_items.each do |order_item| %>
    <tr>
      <td><%= order_item.product.name %></td>
      <td><%= order_item.quantity %></td>
      <td><%= order_item.price %></td>
      <td><%= order_item.tax_rate %></td>
      <td><%= sprintf("%.2f", order_item.total_price) %></td>
  <% end %>
</table>
<br>
<%= "Total order amount is: #{sprintf("%.2f", @order.amount)}" %><br>
<%= "Total order tax is: #{sprintf("%.2f", @order.tax)}" %><br>
<br>
<br>
<%= link_to 'Pay', pay_orders_path(id: @order.id), method: :post if @order.status == "unpaid" %>
<br>
<br>
<%= link_to 'All orders', orders_path  if current_user.admin? %>
<%= link_to 'Back to your Profile', profile_users_path %>