config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get '/profile', to:"users#profile", as: "profile"
      get '/profile/update', to: 'users#profile_settings', as: "update_profile"
      get '/login', to: 'sessions#new'
    end
  end
  resources :carts, only: [:destroy] do
    collection do
      patch '/update', to: "carts#update_quantity", as: "update_quantity"
      post '/add_item', to: "carts#add_item", as: "add_item"
      delete '/remove_item', to: "carts#remove_item", as: "remove_item"
      get '/display', to: "carts#show"
    end
  end 
  resources :products
  resources :orders do
    collection do
      patch '/:id/process_payment', to: 'orders#process_payment', as: "process_payment"
      post '/:id/pay', to: "orders#payment", as: "pay"
    end
  end
  resources :sessions, only: [] do
    collection do 
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
    end
  end
  root 'welcome#index'
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items 

  def sub_total
    self.cart_items.inject(0){ |cost, item| cost += item.total_price } 
  end
  
  def total_tax
    self.cart_items.inject(0){ |cost, item| cost += item.quantity * item.product.price * item.product.tax_rate / 100 }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  skip_before_action :admin_user?, except: :destroy
  before_action :load_item, except: [:show, :add_item, :destroy]
  before_action :find_product, only: :add_item

  def show
    
  end

  def add_item
    # If cart already has this product then find the relevant cart_item and iterate quantity otherwise create a new cart_item for this product
    if is_present?(@product)
      # Find the cart_item with the @chosen_product
      @cart_item = current_user.cart.cart_items.find_by(product_id: @product.id)
      flash[:danger] = "Item present in cart, update quantity if needed" 
    else
      details = { cart_id: current_user.cart.id, product_id: @product.id, quantity: 1,
                  total_price: @product.price * (1 + @product.tax_rate / 100) }  
      current_user.cart.cart_items.create(details)
    end 
    redirect_to display_carts_path
  end

  def destroy
    current_user.cart.destroy
    redirect_to profile_users_path
  end

  def update_quantity
    if params[:cart_item][:quantity].to_i <= 0
      flash[:danger] = "Quantity can not be less than 1"  
    elsif @cart_item.product.stock - params[:cart_item][:quantity].to_i <= 0
      flash[:danger] = "Product in stock is less than its quantity in cart"
    else
    	details = cart_item_params
    	details[:total_price] = params[:cart_item][:quantity].to_i * @cart_item.product.price * (1 + @cart_item.product.tax_rate / 100)
      unless @cart_item.update_attributes(details)
        flash[:danger] = @cart_item.errors.full_messages
      end
    end
    redirect_to display_carts_path
  end

  def remove_item
    @cart_item.destroy
    redirect_to display_carts_path
  end

  private

  def load_item
    @cart_item = CartItem.find(params[:item_id]) rescue nil
    if @cart_item.blank?
      flash[:danger] = "This Item Does not exists"
      redirect_to display_carts_path
    elsif @cart_item.cart != current_user.cart
      flash[:danger] = "This Item Does not belongs to your cart"
      redirect_to display_carts_path
    end
  end

  def find_product
    @product = Product.find(params[:product_id]) rescue nil
    if @product.blank?
      flash[:danger] = "Product does not exists"
      redirect_to products_path
    elsif @product.stock == 0
      flash[:danger] = "Product is out of stock! We will notify you whenever it is back in stock"
      redirect_to products_path
    end
  end

  def is_present?(product)
    current_user.cart.cart_items.exists?(product_id: product.id)
  end

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div class="wrapper">
  <marquee behavior="alternate"><span class="marquee">
    <h4>
      <% if current_user.cart.cart_items.blank? %>
        <%= "Cart is empty, please Add items to cart"  %>
      <% else %>
      <%= "Do not forget to press enter after updating quantity" %>
      <% end %>
    </h4></span>
  </marquee>
</div>
<% if current_user.cart.cart_items.present? %>
<h2>Your Cart </h2>
<table>
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Tax rate</th>
    <th>Amount</th>
    <th colspan="3"></th>
  </tr>
  <% current_user.cart.cart_items.each do |cart_item| %>
    <tr>
      <td><%= cart_item.product.name %></td>
      <td><%= cart_item.quantity %></td>
      <td><%= cart_item.product.price %></td>
      <td><%= cart_item.product.tax_rate %></td>
      <td><%= sprintf("%.2f", cart_item.total_price) %></td>
      <td><%= form_for cart_item, url: url_for(update_quantity_carts_path(item_id: cart_item.id)),
              remote: true do |f| %>
              <%= f.number_field :quantity %>
          <% end %><td>
      <td><%= button_to "Remove item", remove_item_carts_path(item_id: cart_item.id), method: :delete, 
              remote: true  %><td>
      <td colspan="5"></td>
  <% end %>
</table>
<br>
<%= "Total Cart Amount: #{sprintf("%.2f",current_user.cart.sub_total)}" %><br>
<%= "Total Cart Tax: #{sprintf("%.2f",current_user.cart.total_tax)}" %><br>
<br>
<%= link_to "Proceed to checkout", new_order_path %>
<% end %>
<%= link_to "Add items", products_path %>
<%= link_to "Back to your profile", profile_users_path %>