config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get '/profile', to:"users#profile", as: "profile"
      get '/profile/update', to: 'users#profile_settings', as: "update_profile"
      get '/login', to: 'sessions#new'
    end
  end
  resources :carts, only: [:destroy] do
    collection do
      patch '/update', to: "carts#update_quantity", as: "update_quantity"
      post '/add_item', to: "carts#add_item", as: "add_item"
      delete '/remove_item', to: "carts#remove_item", as: "remove_item"
      get '/display', to: "carts#show"
    end
  end 
  resources :products
  resources :orders do
    collection do
      patch '/:id/process_payment', to: 'orders#process_payment', as: "process_payment"
      post '/:id/pay', to: "orders#payment", as: "pay"
    end
  end
  resources :sessions, only: [] do
    collection do 
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
    end
  end
  root 'welcome#index'
end

app/models/product.rb
class Product < ApplicationRecord

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  has_many :cart_items
  has_many :order_items
  validates :stock, numericality: { greater_than_or_equal_to: 0 }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  skip_before_action :admin_user?, only: [:index, :show]
  before_action :load_product, except: [:index, :new, :create]
  
  def index
    @products = Product.all
  end

  def show
    
  end

  def new
    @product = Product.new
  end

  def edit
    
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product created!"
      redirect_to @product
    else
      render 'new'
    end
  end

  def update
    if @product.update_attributes(product_params) 
      flash[:success] = "Product updated!"
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def load_product
    @product = Product.find(params[:id]) rescue nil
    if @product.blank?
      flash[:danger] = "product does not exits"
      redirect_to products_path
    end
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :tax_rate, 
                                    :cod, :stock, :shipping_charge_rate, :avatar)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <%= render partial: 'shared/error_messages', locals: {object: @product} %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :stock %><br>
    <%= f.text_field :stock %>
  </p>
  <p>
    <%= f.label :tax_rate %><br>
    <%= f.text_field :tax_rate %>
  </p>
  <p>
    <%= f.label :cod %><br>
    <%= f.text_field :cod %>
  </p>
  <p>
    <%= f.label :shipping_charge_rate %><br>
    <%= f.text_field :shipping_charge_rate %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :avatar %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Update Product Details</h1>
<%= render 'form' %>
<%= link_to 'Back to profile', profile_users_path %>

app/views/products/index.html.erb
<h1>All products</h1>
<table>
  <tr>
    <th>NAME</th>
    <th>Image</th>
    <th>PRICE</th>
    <th>STOCK</th>
    <th colspan="3"></th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= image_tag product.avatar.url(:thumb) %></td>
      <td><%= product.price %></td>
      <td><%= product.stock %></td>
      <td><%= button_to 'Add to Cart', add_item_carts_path(product_id: product.id), method: :post %></td>
      <td><%= link_to 'View complete details', product_path(product) %></td>
      <td><%= button_to 'Remove product', product_path(product), method: :delete,
              data: { confirm: 'Are you sure?' }  if current_user.admin? %></td>
  <% end %>
</table>
<%= link_to 'Back to your profile', profile_users_path %>
<%= link_to 'Go to cart', display_carts_path %>
<%= link_to 'Add product', new_product_path if current_user.admin? %>

app/views/products/new.html.erb
<h1>Create Product</h1>
<%= render 'form' %>
<%= link_to 'Back to profile', profile_users_path %>

app/views/products/show.html.erb
<%= "Hey Admin!, create or update products" if current_user.admin? %>
<p>
  <strong>NAME:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>DESCRIPTION:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>PRICE:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>STOCK:</strong>
  <%= @product.stock %>
</p>
<p>
  <strong>TAX RATE:</strong>
  <%= @product.tax_rate %>
</p>
<p>
  <strong>COD:</strong>
  <%= @product.cod %>
</p>
<p>
  <strong>Shipping Charge Rate:</strong>
  <%= @product.shipping_charge_rate %>
</p>
<p>
  <strong>Image:</strong><br>
  <%= image_tag @product.avatar.url(:medium) %>
</p>
<%= button_to 'Add to Cart', add_item_carts_path(product_id: @product.id), method: :post %>
<%= link_to 'products List', products_path %>
<%= link_to 'Update product', edit_product_path if current_user.admin? %>
<%= link_to 'Go to cart', display_carts_path %>
<%= link_to 'Back to profile', profile_users_path %>